### ISSUE TITLE
[Question] There is a WebHook tab in developer.ringcentral.com app settings page

### ISSUE THREAD

**Issue by tylerlong** [grokify/glipbot-bootstrap#1]
There is a WebHook tab in developer.ringcentral.com app settings page. 

You can configure WebHook there and a WebHook could be auto created for you after you click the "add to Glip" button.

Question is:  What are the differences between this project and the WebHook tab in developer.ringcentral.com?

One advantage of this project is: I can create the WebHook afterwards at any time which is flexible. Any other advantages?

**Comment by grokify** [comment]
Good question. The WebHook tab in the Developer Portal (https://developer.ringcentral.com) is good when you want to add a private bot to your own company's account.

This provides additional functionality when developing a public bot where you want to create webhook subscriptions to other accounts for testing purposes, for example building a bot on a free developer account and then having it access your corporate account. Of course, for a public bot, you will eventually want the webhooks to be auto-created by your bot but this can be useful to phase development.
